### ISSUE TITLE
Add native gRPC support to the dotnet client

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/armada#1030]
dotnet supports generating grpc clients from proto files, update the client to use this approach.

Tagged as a stability issue b/c we have a large number of issues with the REST client that could be mitigated w/grpc.

ARMADA-1098

**Comment by d80tb7** [comment]
@andrewpcone If you look at https://github.com/G-Research/armada/tree/f/chrisma/dotnetclient I've got a bit of code you might be able to use as a start for this.  The basic strategy is:

- Create a new Solution under `client/DotNet.gRPC/Armada.Client.Grpc` with the intention of releasing the grpc client as a completely separate library.  Once this client is mature we can decomission the old rest client.
- Modify `build/proto/Dockerfile` such that the Docker image it creates is capable of generating dotnet code.  The only real change here is to download `grpc_csharp_plugin` from nuget and make it available to protoc.
- Modify `scripts/proto.sh` to generate dotnet code under `client/DotNet.gRPC/Armada.Client.Grpc/generated`

Note that the new `Armada.Client.Grpc` solution basically has nothing in it when you check out of git.  This is intentional and the idea is that a developer must first run `make proto` to  add the generated code to the project.  

Things that are not done/well-resolved
- Whether the client should consist of anything other than the generated code.  My feeling here is that it shouldn't because the generated code is pretty much enough, but others may disagree.  @severinson or @JamesMurkin may have opinions here.
- Any sort of tests.  If we just go with the just generated code we probably don't need unit tests. It would be nice to have an e2e test, however.
- An example of how to use the client.  We could possible create an examples project inside the `Armada.Client.Grpc` solution for this.
- Documentation.
- If you look at the generated code, I generate classes for our gogoproto, k8s.io etc dependencies.  We need these classes to be available to users because when they submit an armada job they are going to have to be able to create for example a k8s.io podspec.  What this means, however is that our `Armada.Client.Grpc` library is going to be publishing classes in a  `k8s.io` namespace which seems like bad etiquette.  It might be worth finding some grpc/dotnet expert and seeing what the solutionf for this should be.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1030?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by kannon92** [comment]
This issue can be closed.  There are a few items left over but the main bulk of this work is complete.
