### ISSUE TITLE
Python client: Add a release step where we release python-client 

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1072]
We should create a wheel file and upload it to PyPI.  

1) Add a GHA that builds/publishes our package to pypi.  
2) Should update version with changes/

Questions:

What email should we use for Pypi?

**Comment by kannon92** [comment]
Update:

We created a new account in PYPI for Armada:

armada@armadaproject.io with the username Armada-GROSS.  

A manual upload process is as follows:

1) Go to the Armada-GROSS account on PyPI and log on.
2) Generate the API tokens and copy those tokens to ~/.pypirc.
3) cd client/python
4) `poetry build`
5) `poetry run twine upload dist/*`

**Comment by jayofdoom** [comment]
The output for this issue should be:
- Internal documentation on how to tag and release an armada python client
- Automatically perform releases, and push to pypi, when above criteria is met
- Determine and document versioning system for armada python client

**Comment by rankindaveyg** [comment]
5

**Comment by jayofdoom** [comment]
This issue is blocked.

Code supporting this has all been merged to master. It cannot be tested until someone, with access to publish secrets to g-research/armada, does the following:

- login to pypi
- create a new token, scoped to uploading armada-client only
- put that token in as a secret named `PYPI_API_TOKEN`

Alternatively, I can create the token and upload the secret myself if given permission, or if given a secure way to handoff the token I already created.


At that time, if you go to https://github.com/G-Research/armada/actions/workflows/python-client-release-to-pypi.yml, you should be able to run the workflow against master and it will release `0.2.0` to pypi (unless there are bugs, given I've been unable to test yet).

After that works, we need to validate that pypi will not allow us to upload another 0.2.0 and document the process for releasing this (basically, commit a change to pyproject.toml raising the version to what you want, then run the workflow).

**Comment by kannon92** [comment]
Hey @jayofdoom I think we can close this issue.  

https://pypi.org/project/armada-client/

We were able to publish from a manual action with our new credentials!
