### ISSUE TITLE
Discussion: Should we enable the linter to fail if the golangci linter catches a lint issue?

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1448]
We currently enable the linter to return an exit code of 1 if the linter detects an issue.  This causes the CI to mark the PR as failed.  

There is some discussion about what is the best way forward for a linter job:

a) We should enable the linter as job that will fail if someone commits code that fails the lint check.

b) We can have the linter run in the action but not report an error if it detects a linter issue.  

c) We can just remove the linter and use goimports/gofmt as a default setting.  

d) Provide more relaxed linters that catch actual code issues.

I believe these are the ideas thrown around internally as options for the linter.

**Comment by kannon92** [comment]
My thoughts:

In general, optional CI jobs tend to be ignored by developers.  If we go with a linter that doesn't fail the build, then it is the engineers job to run that as part of the workflow or for the reviewer to look for lint issues.  Ideally, having this as part of setup allows engineers to focus on code review rather than formatting/linting.  

Linting does provide overhead to a developers workflow as they have to run command or set up their IDE to catch lint issues.  However, this isn't required for an optional job so some developers don't have to set this up.

The linter action will open up issues in the PR but do we actually enforce these as part of the PR?

**Comment by suprjinx** [comment]
I wonder if there's a way to apply the "run --fix" (and perhaps golines) as a new commit to the PR automatically if needed (filtered to just run on the touched files)

**Comment by d80tb7** [comment]
So I think a) (having the linter fail the CI) is the right choice.  Having a consistent  coding standard is important if we want to have a wide group of developers and you're right that if the CI doesn't fail, it will be difficult to enforce this.

The important thing though is that we don't unforce this until we have made it relatively frictionless for developers to use.  Essentially we want to make it as easy as possible for developers to get to work on Armada and to avoid the situation where someone doesn't make a PR just because they can't work out (or don't want to invest the time) in making their code conform to the linting rules.

I think in an ideal world we'd have something like the following:
1) A section in the development guide which explains what the linting style is.
2. A section in the development guide which explains how to set up common ides to automatically format to this linting style (I doubt we'll be able to get to a 100% match here, but it should mean that the vast majority of the code written will conform to the style before you get to the point where you raise a PR).
3. A section in the development guide which explains how you can check (and ideally fix) your code before committing.  Possibly we could also provide a webhook here that would do this automatically.
4. Clear and quick CI that tells you what linting rules have failed and why.

I think if we have this then life will become much better for people who regularly work on Armada.  If we want to encourage people to provide on-off pull requests then we have an extra requirement which is to ensure that all of the setup mentioned above can be done quickly and easily as if it involves a hour of installing and configuring tools and ides, it'll put a lot of people off even attempting to submit a PR[1].


[1] I realise that this is a more general problem than just linters in that there are other aspects of armada development that make it difficult for a newcomer to get up and running.

**Comment by kannon92** [comment]
Hey @d80tb7, glad we are in agreement on this.  

I realize we could've done this better but I feel that removing it at this point seems counterproductive.  

In order to get our CI to pass, we had to go through and auto apply these linter fixes and review the changes to make sure that there wasn't any egregious failures of auto applying the linter.  We noticed that the auto fix isn't the most robust so we did actually review every line of code that was applied by the linter.  Thanks to @jayofdoom ! for pointing this out.  In order to get our initial linter to work, we had to review over 180 files. 

I kinda view this as a forcing function for developers to download the linter and actually apply these changes.  

If we disable it now, someone is going to have to reapply the linter and get the code base to be compliant with the linter.  I don't know if we will prioritize that work above other features.

**Comment by kannon92** [comment]
> I wonder if there's a way to apply the "run --fix" (and perhaps golines) as a new commit to the PR automatically if needed (filtered to just run on the touched files)

I think github auth may make that weird.  I personally would prefer that developers commit the PR rather than some github bot.  I find having service accounts committing code is usually a pain.  

I know that there was an option thrown around about using a git hook but I have bad experience with that.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1448?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1448?planning-poker) with Zenhub @suprjinx
