### ISSUE TITLE
Server: better validation error messages

### ISSUE THREAD

**Issue by samclark** [G-Research/armada#1488]
When submitted jobs are rejected by armada users would like to see the reason they are rejected.

e.g. you have requested too many cpus / memory / gpus
e.g. there are nodes capable of running your job but they are tainted with taints you have not tolerated.
e.g. there are nodes capable of running your job but you have included a node selector / node affinity which doesn't target them

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1488?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by ClifHouck** [comment]
I'm going to take a look at this.

**Comment by ClifHouck** [comment]
At least in the case of memory it seems like armada server *does* return a detailed reason why a podspec is rejected if the amount of requested memory is too big for any available node to service. Example: `0-th job can't be scheduled: can't schedule pod on any node type: 1 node type(s) excluded because pod requested 137438953472.000000 of resource memory, but only 67342204928.000000 is available`. At least in this case I can understand the desire to have the numbers be made more human readable, but the error message *does* include the exact reason why the job was rejected.

**Comment by ClifHouck** [comment]
@samclark How are you submitting jobs to armada? Which client?

**Comment by severinson** [comment]
I believe this has already been solved by this PR:
https://github.com/G-Research/armada/pull/983

I'll close the issue for now.
