### ISSUE TITLE
Jobservice can still run into SQL_BUSY errors when trying to write to the job service table

### ISSUE THREAD

**Issue by ClifHouck** [G-Research/armada#1563]
Related to https://github.com/G-Research/armada/issues/1544

Locking around executing write queries seems to greatly reduce the chance of running into SQL_BUSY errors in the jobservice, but doesn't eliminate the chance. Need to figure out a more robust solution. 

Some possible avenues:

- Use [Write Ahead Logging](https://www.sqlite.org/wal.html)
- Add some retry logic to statements that error out due to SQL_BUSY.
- Use a different DB?

**Comment by ClifHouck** [comment]
I'll take a look at this.

**Comment by kannon92** [comment]
@richscott you have anything to add? 

One other possible avenue is to enable a cache layer.  I originally had an in memory map of jobs and I would batch write to the db separately.  But we decided to remove that as we thought it would be premature optimization.

**Comment by richscott** [comment]
Using a WAL will definitely improve performance (Postgresql always uses a WAL, btw), but I am not sure about the operational semantics/correctness of using it when SQLite is operating inside a K8S virtual container with mounted filesystem - is the fsync(int fd) behavior reliably the same as on native disk, and is the performance good?

Adding retry logic might be worthwhile, but will we need to apply it everywhere, not just the queries/updates we've seen failing so far?

Re using a different DB - migrating to Postgres (most Armada installations would have Postgres running, since it's a component of Lookout) would remove this issue, since Postgres allows many concurrent write transactions due to its MVCC logic for handling concurrency.  (At previous gigs, we've had write-intensive applications use >200 concurrent connections and Postgres had no problem handling them.)  But switching db's is a big change, it will take code changes, configuration changes, deployment process steps, etc etc.

I'd be averse to adding caching code to batch up pending changes and insert/update the db en masse - would we still get SQL_BUSY errors on interleaved reads during pending commits? And more basically, I'd rather let the database just handle concurrency, rather than us writing code to work around by doing forced sequential processing.

**Comment by ClifHouck** [comment]
Quick update: Using `PRAGMA journal_mode=WAL` with my concurrency test seems to completely eliminate SQLITE_BUSY errors, and the test is also faster as a result.

**Comment by kannon92** [comment]
That's great! Before we merge, I say we should stress test a bit more than we have.  Running test multiple times and bumping up the concurrency of that test.  Not comitting it though but just to make sure if it is possible to see this.

**Comment by ClifHouck** [comment]
Assuming WAL holds up against more stressful tests, should I still pursue some retry logic with backoff or skip it for now?

**Comment by richscott** [comment]
Eh, I'm of the "do the least amount of engineering until the situation is fully understood" school, as writing more logic around retries would introduce complexities in the overall behavior - I say we wait until we see if it's still an issue after the WAL change.

**Comment by kannon92** [comment]
One thing we maybe should relax is panicing if SQL Busy happens.  I realize that if we fail an update once I don't think we should bring down the service.  

WDYT?

**Comment by ClifHouck** [comment]
If I bump concurrency to 1000 and run the test 100 times I start running into occasional semaphore acquisition panics.

Bumping concurrency to 10000 passes but the test takes a minute. A single run with 100000 starts to run into semaphore acquisition errors again.

So if we reach the level of concurrency to cause semaphore failures we're probably well into the territory of needing to find a different SQL back-end.

@kannon92 :+1: to handling the error more gracefully than panicing. I'll work on that and then post a PR with what I have so far.
