### ISSUE TITLE
Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/armada#1591]

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1591?planning-poker) with Zenhub @ClifHouck @richscott @suprjinx @dejanzele @Sharpz7

**Comment by kannon92** [comment]
Should we hold on adding Armada to the maintainers list until we migrate to our own repo?  We can do the first part of this ticket without any issue.

**Comment by stackedsax** [comment]
I think we can do this before moving to its own repo.  In fact, it will probably help CNCF folks find us with important information about Sandboxing.

Amye at the CNCF suggested that the `project-maintainers.md` file in the foundation repo is maybe a shorter list than the `maintainers.md` file we maintain in our repo.  I made a stab at it here: 

* https://github.com/cncf/foundation/compare/main...G-Research:foundation:stackedsax-add_armada_maintainers

I may have the wrong list of people -- adjust to taste.

The only thing my commit is missing is a reference to our `maintainers.md` file because we don't have one yet.  That could be a longer list of all the people on the project who have maintainer rights.

**Comment by kannon92** [comment]
https://github.com/cncf/foundation/pull/439

**Comment by kannon92** [comment]
Merged.
